<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_yt2cd87659880ee6b',
		'title' => 'Information',
		'fields' => array(
			array(
				'key' => 'field_gl632c8df65945b',
				'label' => 'Information',
				'name' => 'info',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			
			
			array(
				'key' => 'field_ddz891427c3443',
				'label' => 'Details',
				'name' => 'details',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_gl632c89bde6278',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_team_field field="title"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_glggg2c89bde6278',
						'label' => 'Phone',
						'name' => 'phone',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_team_field field="phone"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_gl632c89cde6279',
						'label' => 'Email',
						'name' => 'email',
						'type' => 'email',
						// 'instructions' => 'Short Code: [n3_team_field field="email"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_gl632c89dee627a',
						'label' => 'Position',
						'name' => 'position',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_team_field field="position"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6ddfdd32c8c21e627d',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'link',
						// 'instructions' => 'Short Code: [n3_team_field field="url"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
					array(
						'key' => 'field_gl632c8c04e627c',
						'label' => 'File',
						'name' => 'file',
						'type' => 'file',
						// 'instructions' => 'Short Code: [n3_team_field field="file_url"], [n3_team_field field="file_name"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
			
			array(
				'key' => 'field_uuu891427c3443',
				'label' => 'Location Information',
				'name' => 'location_information',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(	
					array(
						'key' => 'field_yp63f184cbeb144',
						'label' => 'City',
						'name' => 'city',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_team_field field="city"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					// County	
					array(
						'key' => 'field_qqq63f184cbeb144',
						'label' => 'County',
						'name' => 'county',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_team_field field="county"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_yp63f1851deb145',
						'label' => 'State',
						'name' => 'state',
						'aria-label' => '',
						'type' => 'select',
						// 'instructions' => 'Short Code: [n3_team_field field="state"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'AL' => 'Alabama',
							'AK' => 'Alaska',
							'AZ' => 'Arizona',
							'AR' => 'Arkansas',
							'CA' => 'California',
							'CO' => 'Colorado',
							'CT' => 'Connecticut',
							'DE' => 'Delaware',
							'DC' => 'District of Columbia',
							'FL' => 'Florida',
							'GA' => 'Georgia',
							'HI' => 'Hawaii',
							'ID' => 'Idaho',
							'IL' => 'Illinois',
							'IN' => 'Indiana',
							'IA' => 'Iowa',
							'KS' => 'Kansas',
							'KY' => 'Kentucky',
							'LA' => 'Louisiana',
							'ME' => 'Maine',
							'MD' => 'Maryland',
							'MA' => 'Massachusetts',
							'MI' => 'Michigan',
							'MN' => 'Minnesota',
							'MS' => 'Mississippi',
							'MO' => 'Missouri',
							'MT' => 'Montana',
							'NE' => 'Nebraska',
							'NV' => 'Nevada',
							'NH' => 'New Hampshire',
							'NJ' => 'New Jersey',
							'NM' => 'New Mexico',
							'NY' => 'New York',
							'NC' => 'North Carolina',
							'ND' => 'North Dakota',
							'OH' => 'Ohio',
							'OK' => 'Oklahoma',
							'OR' => 'Oregon',
							'PA' => 'Pennsylvania',
							'RI' => 'Rhode Island',
							'SC' => 'South Carolina',
							'SD' => 'South Dakota',
							'TN' => 'Tennessee',
							'TX' => 'Texas',
							'UT' => 'Utah',
							'VT' => 'Vermont',
							'VA' => 'Virginia',
							'WA' => 'Washington',
							'WV' => 'West Virginia',
							'WI' => 'Wisconsin',
							'WY' => 'Wyoming',
						),
						'default_value' => array(
							0 => 'TX',
						),
						'return_format' => 'array',
						'multiple' => 0,
						'allow_custom' => 0,
						// 'allow_null' => 0,
						'allow_in_bindings' => 0,
						'custom_choice_button_text' => 'Add new choice',
						'layout' => 'vertical',
						'ui' => 1,
						'ajax' => 1,
						'placeholder' => '',
					),
					array(
						'key' => 'field_yp3f18528eb146',
						'label' => 'Country',
						'name' => 'country',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_team_field field="country"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
			),
			array(
				'key' => 'field_632cmm8c74e627e',
				'label' => 'Social',
				'name' => 'social',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_63ml2c8c99e627f',
				'label' => 'Facebook URL',
				'name' => 'facebook',
				'type' => 'url',
				// 'instructions' => 'Short Code: [n3_team_field field="facebook"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_63ml2c8cb7e6280',
				'label' => 'Twitter URL',
				'name' => 'twitter',
				'type' => 'url',
				// 'instructions' => 'Short Code: [n3_team_field field="twitter"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_63ml2c8ce7e6281',
				'label' => 'Instagram URL',
				'name' => 'instagram',
				'type' => 'url',
				// 'instructions' => 'Short Code: [n3_team_field field="instagram"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_63ml2c8d53e6282',
				'label' => 'WhatsApp URL',
				'name' => 'whatsapp',
				'type' => 'url',
				// 'instructions' => 'Short Code: [n3_team_field field="whatsapp"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_63ml2c8d5ce6286',
				'label' => 'TikTok URL',
				'name' => 'tiktok',
				'type' => 'url',
				// 'instructions' => 'Short Code: [n3_team_field field="tiktok"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_63ml2c8d5ce6285',
				'label' => 'Linkedln URL',
				'name' => 'linkedin',
				'type' => 'url',
				// 'instructions' => 'Short Code: [n3_team_field field="linkedin"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_8d5mlce6632c285',
				'label' => 'Youtube URL',
				'name' => 'youtube',
				'type' => 'url',
				// 'instructions' => 'Short Code: [n3_team_field field="youtube"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_gl632c8ebcf2a0c',
				'label' => 'Team Reviews',
				'name' => 'reviews',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_gl632c89fde627b',
				'label' => 'Rank',
				'name' => 'rank',
				'type' => 'range',
				// 'instructions' => 'Short Code: [n3_team_field field="rank"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'min' => 1,
				'max' => 5,
				'step' => '1',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_gl632c8efcf2a0d',
				'label' => 'Date',
				'name' => 'date',
				'type' => 'date_picker',
				// 'instructions' => 'Short Code: [n3_team_field field="date"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'm/d/Y',
				'return_format' => 'm/d/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_gl632c8c21e627d',
				'label' => 'URL',
				'name' => 'url',
				'type' => 'link',
				// 'instructions' => 'Short Code: [n3_team_field field="rank_url"], [n3_team_field field="rank_title"], [n3_team_field field="rank_target"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			)
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'n3_teams',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	endif;		