<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_532c89880ee6b',
		'title' => 'Information',
		'fields' => array(
			array(
				'key' => 'field_g632c8df65945b',
				'label' => 'Job Information',
				'name' => 'info',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_g632c8c04e627c',
				'label' => 'File',
				'name' => 'file',
				'type' => 'file',
				// 'instructions' => 'Short Code: [n3_career_field field="file_name"], [n3_career_field field="file_url"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_g632c89bde6278',
				'label' => 'Job Type',
				'name' => 'type',
				'type' => 'text',
				// 'instructions' => 'Short Code: [n3_career_field field="type"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.333333',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_g632c89dee627a',
				'label' => 'Position',
				'name' => 'position',
				'type' => 'text',
				// 'instructions' => 'Short Code: [n3_career_field field="position"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.333333',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			// Create Date
			array(
				'key' => 'field_g6dscdd21e627d',
				'label' => 'Create Date',
				'name' => 'create_date',
				'type' => 'date_picker',
				// 'instructions' => 'Short Code: [n3_career_field field="create_date"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.333333',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'm/d/Y',
				'return_format' => 'm/d/Y',
				'first_day' => 1,
			),
			// Expire Date
			array(
				'key' => 'field_g632cdd21e627d',
				'label' => 'Expire Date',
				'name' => 'expire_date',
				'type' => 'date_picker',
				// 'instructions' => 'Short Code: [n3_career_field field="expire_date"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33.333333',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'm/d/Y',
				'return_format' => 'm/d/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_y63f184cbeb144',
				'label' => 'City',
				'name' => 'city',
				'aria-label' => '',
				'type' => 'text',
				// 'instructions' => 'Short Code: [n3_career_field field="city"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_y63f1851deb145',
				'label' => 'State',
				'name' => 'state',
				'aria-label' => '',
				'type' => 'checkbox',
				// 'instructions' => 'Short Code: [n3_career_field field="state"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'AL' => 'Alabama',
					'AK' => 'Alaska',
					'AZ' => 'Arizona',
					'AR' => 'Arkansas',
					'CA' => 'California',
					'CO' => 'Colorado',
					'CT' => 'Connecticut',
					'DE' => 'Delaware',
					'DC' => 'District of Columbia',
					'FL' => 'Florida',
					'GA' => 'Georgia',
					'HI' => 'Hawaii',
					'ID' => 'Idaho',
					'IL' => 'Illinois',
					'IN' => 'Indiana',
					'IA' => 'Iowa',
					'KS' => 'Kansas',
					'KY' => 'Kentucky',
					'LA' => 'Louisiana',
					'ME' => 'Maine',
					'MD' => 'Maryland',
					'MA' => 'Massachusetts',
					'MI' => 'Michigan',
					'MN' => 'Minnesota',
					'MS' => 'Mississippi',
					'MO' => 'Missouri',
					'MT' => 'Montana',
					'NE' => 'Nebraska',
					'NV' => 'Nevada',
					'NH' => 'New Hampshire',
					'NJ' => 'New Jersey',
					'NM' => 'New Mexico',
					'NY' => 'New York',
					'NC' => 'North Carolina',
					'ND' => 'North Dakota',
					'OH' => 'Ohio',
					'OK' => 'Oklahoma',
					'OR' => 'Oregon',
					'PA' => 'Pennsylvania',
					'RI' => 'Rhode Island',
					'SC' => 'South Carolina',
					'SD' => 'South Dakota',
					'TN' => 'Tennessee',
					'TX' => 'Texas',
					'UT' => 'Utah',
					'VT' => 'Vermont',
					'VA' => 'Virginia',
					'WA' => 'Washington',
					'WV' => 'West Virginia',
					'WI' => 'Wisconsin',
					'WY' => 'Wyoming',
				),
				'default_value' => array(
					0 => 'TX',
				),
				'return_format' => 'array',
				'multiple' => 1,
				'allow_custom' => 1,
				// 'allow_null' => 0,
				'allow_in_bindings' => 0,
				'custom_choice_button_text' => 'Add new choice',
				'layout' => 'vertical',
				'ui' => 1,
				'ajax' => 1,
				'placeholder' => '',
			),
			array(
				'key' => 'field_y3f18528eb146',
				'label' => 'Country',
				'name' => 'country',
				'aria-label' => '',
				'type' => 'text',
				// 'instructions' => 'Short Code: [n3_career_field field="country"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_g632c8ebcf2a0c',
				'label' => 'Job Reviews',
				'name' => 'reviews',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_g632c89fde627b',
				'label' => 'Rank',
				'name' => 'rank',
				'type' => 'range',
				// 'instructions' => 'Short Code: [n3_career_field field="rank"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'min' => 1,
				'max' => 5,
				'step' => '1',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_g632c8efcf2a0d',
				'label' => 'Date',
				'name' => 'date',
				'type' => 'date_picker',
				// 'instructions' => 'Short Code: [n3_career_field field="date"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'm/d/Y',
				'return_format' => 'm/d/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_g632c8c21e627d',
				'label' => 'URL',
				'name' => 'url',
				'type' => 'link',
				// 'instructions' => 'Short Code: [n3_career_field field="rank_url"], [n3_career_field field="rank_title"], [n3_career_field field="rank_target"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			)
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'n3_careers',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	endif;		