<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_a532c89880ee6b',
		'title' => 'Information',
		'fields' => array(
			array(
				'key' => 'field_bg632c8df65945b',
				'label' => 'Property Information',
				'name' => 'info',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			// Property Status
			array(
				'key' => 'field_vg632c8c04e627c',
				'label' => 'Property Status',
				'name' => 'property_status',
				'type' => 'button_group',
				// 'instructions' => 'Short Code: [n3_property_field field="property_status"]',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'active' => 'Active',
					'escrow' => 'Escrow',
					'pending' => 'Pending',
					'sold' => 'Sold',
					'closed' => 'Closed',
				),
				'return_format' => 'value',
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'layout' => 'horizontal',
				'ui' => 1,
				'ajax' => 1,
				'placeholder' => '',
			),			
			array(
				'key' => 'field_lll891427c3443',
				'label' => 'General',
				'name' => 'general',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(		
					array(
						'key' => 'field_mg632c8c04e627c',
						'label' => 'Property Type',
						'name' => 'property_type',
						'type' => 'select',
						// 'instructions' => 'Short Code: [n3_property_field field="property_type"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'land' => 'Land',
							'commercial' => 'Commercial',
							'mixed' => 'Mixed',
							'mixed-use' => 'Mixed-Use',
							'residential' => 'Residential',
							'restaurant' => 'Restaurant',
							'retail' => 'Retail',
							'office' => 'Office',
						),
						'return_format' => 'value',
						'allow_null' => 0,
						'allow_custom' => 1,
						'multiple' => 1,
						'allow_in_bindings' => 0,
						'layout' => 'vertical',
						'ui' => 1,
						'ajax' => 1,
						'placeholder' => '',
					),					
					array(
						'key' => 'field_og632c8c04e627c',
						'label' => 'Offering Type',
						'name' => 'offering_type',
						'type' => 'select',
						// 'instructions' => 'Short Code: [n3_property_field field="offering_type"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'sale' => 'Sale',
							'lease' => 'Lease',
						),
						'return_format' => 'value',
						'allow_null' => 0,
						'allow_custom' => 1,
						'multiple' => 1,
						'allow_in_bindings' => 0,
						'layout' => 'vertical',
						'ui' => 1,
						'ajax' => 1,
						'placeholder' => '',
					),	
					// Year Built
					array(
						'key' => 'field_bg6dscdd21e627d',
						'label' => 'Year Built',
						'name' => 'year_built',
						'type' => 'date_picker',
						// 'instructions' => 'Short Code: [n3_property_field field="year_built"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'Y',
						'return_format' => 'Y',
						'first_day' => 1,
					),
					// Surface	
					array(
						'key' => 'field_bgdd732c8c04e627d',
						'label' => 'Surface',
						'name' => 'surface',
						'type' => 'number',
						// 'instructions' => 'Short Code: [n3_property_field field="surface"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '0.01',
					),
					// Surface Unit
					array(
						'key' => 'field_bg732c8c04e627d',
						'label' => 'Surface Unit',
						'name' => 'surface_unit',
						'type' => 'select',
						// 'instructions' => 'Short Code: [n3_property_field field="surface_unit"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'sqft' => 'Square Feet',
							'acre' => 'Acre',
							'm2' => 'Square Meters',
							'hectare' => 'Hectare',
						),
						'default_value' => array(
							0 => 'sqft',
						),
						'return_format' => 'value',
						'allow_null' => 0,
						'allow_custom' => 1,
						'multiple' => 0,
						'allow_in_bindings' => 0,
						'layout' => 'vertical',
						'ui' => 1,
						'ajax' => 1,
						'placeholder' => '',
					),
					// Units Count
					array(
						'key' => 'field_bg932c8c04e627d',
						'label' => 'Units Count',
						'name' => 'units_count',
						'type' => 'number',
						// 'instructions' => 'Short Code: [n3_property_field field="units_count"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '0.01',
					),
					// Price
					array(
						'key' => 'field_bg832c8c04e627d',
						'label' => 'Price',
						'name' => 'price',
						'type' => 'number',
						// 'instructions' => 'Short Code: [n3_property_field field="price"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '0.01',
					),
					// Price Postfix
					array(
						'key' => 'field_bgz32c8c04e627d',
						'label' => 'Price Postfix',
						'name' => 'price_postfix',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_property_field field="price_postfix"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'USD',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_bg632cdd21e627d',
						'label' => 'Active Date',
						'name' => 'active_date',
						'type' => 'date_picker',
						// 'instructions' => 'Short Code: [n3_property_field field="active_date"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'm/d/Y',
						'return_format' => 'm/d/Y',
						'first_day' => 1,
					),
				),
			),		
			array(
				'key' => 'field_bzz632c8df65945b',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),	
			array(
				'key' => 'field_zzz891427c3443',
				'label' => 'Location Information',
				'name' => 'location_information',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(	
					// Address
					array(
						'key' => 'field_ba63f184cbeb144',
						'label' => 'Address',
						'name' => 'address',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_property_field field="address"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					// latitude
					array(
						'key' => 'field_lgba63f184cbeb145',
						'label' => 'Latitude',
						'name' => 'latitude',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_property_field field="latitude"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					// longitude
					array(
						'key' => 'field_lgba63f184cbeb146',
						'label' => 'Longitude',
						'name' => 'longitude',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_property_field field="longitude"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_by63f184cbeb144',
						'label' => 'City',
						'name' => 'city',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_property_field field="city"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					// County	
					array(
						'key' => 'field_yyy63f184cbeb144',
						'label' => 'County',
						'name' => 'county',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_property_field field="county"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_by63f1851deb145',
						'label' => 'State',
						'name' => 'state',
						'aria-label' => '',
						'type' => 'select',
						// 'instructions' => 'Short Code: [n3_property_field field="state"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'AL' => 'Alabama',
							'AK' => 'Alaska',
							'AZ' => 'Arizona',
							'AR' => 'Arkansas',
							'CA' => 'California',
							'CO' => 'Colorado',
							'CT' => 'Connecticut',
							'DE' => 'Delaware',
							'DC' => 'District of Columbia',
							'FL' => 'Florida',
							'GA' => 'Georgia',
							'HI' => 'Hawaii',
							'ID' => 'Idaho',
							'IL' => 'Illinois',
							'IN' => 'Indiana',
							'IA' => 'Iowa',
							'KS' => 'Kansas',
							'KY' => 'Kentucky',
							'LA' => 'Louisiana',
							'ME' => 'Maine',
							'MD' => 'Maryland',
							'MA' => 'Massachusetts',
							'MI' => 'Michigan',
							'MN' => 'Minnesota',
							'MS' => 'Mississippi',
							'MO' => 'Missouri',
							'MT' => 'Montana',
							'NE' => 'Nebraska',
							'NV' => 'Nevada',
							'NH' => 'New Hampshire',
							'NJ' => 'New Jersey',
							'NM' => 'New Mexico',
							'NY' => 'New York',
							'NC' => 'North Carolina',
							'ND' => 'North Dakota',
							'OH' => 'Ohio',
							'OK' => 'Oklahoma',
							'OR' => 'Oregon',
							'PA' => 'Pennsylvania',
							'RI' => 'Rhode Island',
							'SC' => 'South Carolina',
							'SD' => 'South Dakota',
							'TN' => 'Tennessee',
							'TX' => 'Texas',
							'UT' => 'Utah',
							'VT' => 'Vermont',
							'VA' => 'Virginia',
							'WA' => 'Washington',
							'WV' => 'West Virginia',
							'WI' => 'Wisconsin',
							'WY' => 'Wyoming',
						),
						'default_value' => array(
							0 => 'TX',
						),
						'return_format' => 'array',
						'multiple' => 0,
						'allow_custom' => 0,
						// 'allow_null' => 0,
						'allow_in_bindings' => 0,
						'layout' => 'vertical',
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_by3f18528eb146',
						'label' => 'Neighborhood',
						'name' => 'neighborhood',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_property_field field="neighborhood"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					// ZIP Code
					array(
						'key' => 'field_by3f18528eb143',
						'label' => 'ZIP Code',
						'name' => 'zip_code',
						'aria-label' => '',
						'type' => 'text',
						// 'instructions' => 'Short Code: [n3_property_field field="zip_code"]',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					// Google Map
					array(
						'key' => 'field_by3f18528eb147',
						'label' => 'Google Map',
						'name' => 'google_map',
						'type' => 'google_map',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'zoom' => '',
						'height' => '',
						'default_value' => array(
							// 'address' => '501 E Broadway Ave, Fort Worth, TX 76104, USA',
							// 'lat' => '32.7365',
							// 'lng' => '-97.3279',
						),
					),
				),
			),
			array(
				'key' => 'field_bg63l2c8ebcf2a0c',
				'label' => 'Availabilities',
				'name' => 'availability',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6789mm2bd64b93c',
				'label' => 'Availabilities',
				'name' => 'availabilities',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Availability',
				'rows_per_page' => 20,
				'sub_fields' => array(
					// Name 
					array(
						'key' => 'field_6789mm2bd64b93d',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field___mm932c8c04e627d',
						'label' => 'Lease Type',
						'name' => 'lease_type',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'na' => 'N/A',
							'gross' => 'Gross',
							'modified_gross' => 'Modified Gross',
							'net_lease' => 'Net Lease',
							'single_net' => 'Single Net (N)',
							'double_net' => 'Double Net (NN)',
							'triple_net' => 'Triple Net (NNN)',
							'absolute_net' => 'Absolute Net',
							'percentage_lease' => 'Percentage Lease',
							'negotiable' => 'Negotiable',
						),
						'default_value' => array(
							0 => 'na',
						),
						'return_format' => 'value',
						'allow_null' => 0,
						'allow_custom' => 1,
						'multiple' => 0,
						'allow_in_bindings' => 0,
						'layout' => 'vertical',
						'ui' => 1,
						'ajax' => 1,
						'placeholder' => '',
					),
					// Surface	
					array(
						'key' => 'field__mmc8c04e627d',
						'label' => 'Surface',
						'name' => 'surface',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '0.01',
					),
					// Surface Unit
					array(
						'key' => 'field__mm732c8c04e627d',
						'label' => 'Surface Unit',
						'name' => 'surface_unit',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'sqft' => 'Square Feet',
							'acre' => 'Acre',
							'm2' => 'Square Meters',
							'hectare' => 'Hectare',
						),
						'default_value' => array(
							0 => 'sqft',
						),
						'return_format' => 'value',
						'allow_null' => 0,
						'allow_custom' => 1,
						'multiple' => 0,
						'allow_in_bindings' => 0,
						'layout' => 'vertical',
						'ui' => 1,
						'ajax' => 1,
						'placeholder' => '',
					),
					// Price
					array(
						'key' => 'field__mm832c8c04e627d',
						'label' => 'Price',
						'name' => 'price',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '0.01',
					),
					// Price Postfix
					array(
						'key' => 'field__mmz32c8c04e627d',
						'label' => 'Price Postfix',
						'name' => 'price_postfix',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'USD',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
			),
			array(
				'key' => 'field_ddfdsdsd5945b',
				'label' => 'Brokers',
				'name' => 'brokers_group',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),	
			// Select Brokers from Users
			array(
				'key' => 'field_bgst632c8df65945b',
				'label' => 'Brokers',
				'name' => 'brokers',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'n3_teams',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'return_format' => 'object',
				'min' => '',
				'max' => '',
				'allow_in_bindings' => 1,
				'elements' => array(
					0 => 'featured_image',
				),
				'bidirectional' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_bss632c8df65945b',
				'label' => 'Property Data',
				'name' => 'data',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),	
			array(
				'key' => 'field_bg632c8c04e627c',
				'label' => 'Brochure',
				'name' => 'brochure',
				'type' => 'file',
				// 'instructions' => 'Short Code: [n3_property_field field="brochure_name"], [n3_property_field field="brochure_url"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_gfvlkj891bbe81ac8',
				'label' => 'Gallery',
				'name' => 'gallery',
				'aria-label' => '',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min' => '',
				'max' => '',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'insert' => 'append',
				'preview_size' => 'thumbnail',
			),
			
			array(
				'key' => 'field_bg632c8ebcf2a0c',
				'label' => 'Reviews',
				'name' => 'reviews',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_bg632c89fde627b',
				'label' => 'Rank',
				'name' => 'rank',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'min' => 1,
				'max' => 5,
				'step' => '1',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_bg632c8efcf2a0d',
				'label' => 'Date',
				'name' => 'date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'm/d/Y',
				'return_format' => 'm/d/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_bg632c8c21e627d',
				'label' => 'URL',
				'name' => 'url',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			)
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'n3_properties',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	endif;		